### PR TITLE
Added Chinese translations

### PR DESCRIPTION
**Pull request by acely**
Added translation for latest develop branch.

### CODE REVIEW

**Comment by acely** [comment]
This one should be right 😆

**Comment by tofi86** [comment]
refs #53 

Thanks for your contribution, @acely! 👍 🎉

**Comment by acely** [comment]
@tofi86 Thank you for this project too 😆

**Comment by tofi86** [comment]
The chinese translation has been released with [version 3.0.0](https://github.com/tofi86/universalJavaApplicationStub/releases/tag/v3.0.0) right now... Thanks for reporting it 👍

**Pull request merged**
