### PR TITLE
Added spanish localization

### PR DESCRIPTION
**Pull request by fvarrui**
**Please check if the PullRequest fulfills these requirements:**

(Add x between brackets to check.)

- [ ] I’ve updated my fork from the `develop` branch before proposing this pull request
- [x] I’m making this pull request against the `develop` branch
- [x] I’ve tested the changes for bug fixes and/or features
- [x] I’ve documented new code

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, other)

Added spanish localization.

**What is the current behavior?** (You can also link to an open issue here)

Not spanish language supported.

**What is the new behavior?**

Now it shows messages in spanish.

**Does this PR introduce a breaking change?** (What changes might users need to make in their application / PList file due to this PR?)

No

**Other information:**

### CODE REVIEW

**Comment by fvarrui** [comment]
Hi @tofi86! I submitted a PR. I take the opportunity to thank you for this amazing script! I'm using it in my [JavaPackager Maven Plugin](https://github.com/fvarrui/JavaPackager).

**Comment by tofi86** [comment]
Awesome! 🎉 Thanks for your contribution! 👏 

Glad you like the script!

**Comment by fvarrui** [comment]
Great! 😃

**Comment by tofi86** [comment]
Version 3.1.0 has officially been released 🎉

Details: https://github.com/tofi86/universalJavaApplicationStub/releases/tag/v3.1.0

**Pull request merged**
