### PR TITLE
Pass command line arguments through to the application

### PR DESCRIPTION
**Pull request by dbankieris**
Currently, you cannot pass command line arguments to the bundled application. For instance:
`open MyJavaApp.app --args arg1 arg2`
`arg1` and `arg2` are available in the `universalJavaApplicationStub` script, but it doesn't forward them in the call to java.
This commit just tacks a `$@` on the end of the call to `exec "$JAVACMD"`

### CODE REVIEW

**Comment by tofi86** [comment]
Thanks for your contribution.

I haven't tested your PR yet, but it looks like the code is missing the `exec` command after your second commit... Did you do proper testing?

**Comment by dbankieris** [comment]
You are correct. Sorry about that. I hadn't actually cloned the repo, just copied the file, onto my machine. So I was editing it locally and then reflecting the changes directly on GitHub via it's editor. Poor form, obviously. I have since cloned it to my machine and pushed the latest commit from there.

**Comment by Albertus82** [comment]
I'm interested in this topic, because I wrote an application that accepts an argument, i.e. a file to open. Now I wonder how the `"Open with..."` feature works in OS X and if it can be replicated for our java apps (I'm not a OS X expert, sorry). Thanks.

**Comment by tofi86** [comment]
@Albertus82 The "Open with…" feature works with registering a specific file extension in your Plist file like for example:

**Jarbundler Ant task:**
```
<jarbundler
		name="EPUB-Checker"
		…
		jvmversion="1.7+">
		
		<documenttype
			name="EPUB files"
			extensions="epub EPUB"
			role="Viewer"
		/>
		
		…
	
</jarbundler>
```

**(generated) Plist snippet:**
```
<plist version="1.0">
  <dict>
    <key>CFBundleDocumentTypes</key>
    <array>
      <dict>
        <key>CFBundleTypeName</key>
        <string>EPUB files</string>
        <key>CFBundleTypeRole</key>
        <string>Viewer</string>
        <key>CFBundleTypeExtensions</key>
        <array>
          <string>epub</string>
          <string>EPUB</string>
        </array>
      </dict>
    </array>
    …
  </dict>
</plist>
```

**Comment by tofi86** [comment]
Thanks for your contribution, @dbankieris!
This will :ship: with version 1.1 (released anytime soon)…

**Comment by tofi86** [comment]
This was added in version 2.0.0 released just today! Thanks for your contribution! 👏

**Comment by Albertus82** [comment]
Hi @tofi86, I upgraded to v2.0.0 but my application won't start anymore :( If I manually open the app folder and start universalJavaApplicationStub, then the app starts along with the terminal window. OS X El Capitan, italian language.

**Comment by tofi86** [comment]
Opening a new issue for that, @Albertus82. See #39

**Comment by tofi86** [comment]
There was a regression in this PR which lead to the bug reported by @Albertus82 in #39.
This should be fixed with 2.0.1 to be released soon...

**Pull request merged**
